"use client"

import React, { useState, useEffect, useRef, useMemo } from "react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Sparkles, RefreshCw, Calendar, Flame, Target, CheckCircle, Clock } from "lucide-react"
import { useUser, useDoc, useMemoFirebase } from "@/firebase"
import { generateMorningBriefing } from "@/app/actions/morning-briefing"
import { format } from "date-fns"
import { useToast } from "@/hooks/use-toast"
import { Skeleton } from "@/components/ui/skeleton"

/**
 * Monica's Morning Briefing Card.
 * Displays real-time intelligence synced with pipeline stats.
 * hasAutoGenerated ref prevents infinite auto-generate loop.
 */
export function MorningBriefingCard() {
  const { user } = useUser();
  const { toast } = useToast();
  const [generating, setGenerating] = useState(false);
  const hasAutoGenerated = useRef(false);

  const today = format(new Date(), 'yyyy-MM-dd');
  const briefingPath = useMemoFirebase(() => {
    if (!user) return null;
    return `users/${user.uid}/morningBriefings/${today}`;
  }, [user, today]);

  const { data: briefing, isLoading } = useDoc(briefingPath);

  useEffect(() => {
    if (user && !briefing && !isLoading && !generating && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleRefresh();
    }
  }, [user, briefing, isLoading]);

  const handleRefresh = async () => {
    if (!user) return;
    setGenerating(true);
    try {
      await generateMorningBriefing(user.uid, today);
      toast({ 
        title: "Intelligence Synced", 
        description: "Monica has analyzed your pipeline for today's session." 
      });
    } catch (err: any) {
      toast({ 
        variant: "destructive", 
        title: "Synthesis Error", 
        description: err.message 
      });
    } finally {
      setGenerating(false);
    }
  };

  const renderBriefingText = (text: string) => {
    return text.split('\n').filter(p => p.trim()).map((p, i) => (
      <p key={i} className={`text-sm leading-relaxed text-blue-50 ${i > 0 ? "mt-4" : ""}`}>
        {p}
      </p>
    ));
  };

  if (!user) return null;

  return (
    <Card className="border-none shadow-xl bg-gradient-to-br from-primary via-primary to-primary/90 text-white overflow-hidden relative group">
      <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none group-hover:scale-110 transition-transform duration-700">
        <Sparkles className="h-32 w-32" />
      </div>
      
      <CardHeader className="pb-4 relative z-10">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-accent rounded-xl shadow-lg ring-1 ring-white/20">
              <Sparkles className="h-5 w-5 text-white" />
            </div>
            <div>
              <CardTitle className="text-xl font-black font-headline">Morning Intelligence</CardTitle>
              <CardDescription className="text-primary-foreground/60 font-bold uppercase tracking-widest text-[10px] flex items-center gap-1.5 mt-0.5">
                <Calendar className="h-3 w-3" /> {format(new Date(), 'EEEE, MMMM do')}
              </CardDescription>
            </div>
          </div>
          <Button 
            variant="ghost" 
            size="icon" 
            onClick={handleRefresh} 
            disabled={generating}
            className="text-white hover:bg-white/10 rounded-full h-10 w-10 transition-all hover:rotate-180"
          >
            <RefreshCw className={`h-4 w-4 ${generating ? 'animate-spin' : ''}`} />
          </Button>
        </div>
      </CardHeader>

      <CardContent className="space-y-6 relative z-10">
        <div className="bg-white/10 rounded-2xl p-5 backdrop-blur-md border border-white/10 shadow-inner min-h-[120px] flex flex-col justify-center">
          {isLoading || generating ? (
            <div className="space-y-3 py-2">
              <Skeleton className="h-4 w-full bg-white/10" />
              <Skeleton className="h-4 w-5/6 bg-white/10" />
              <Skeleton className="h-4 w-4/5 bg-white/10" />
            </div>
          ) : briefing?.briefing_text ? (
            renderBriefingText(briefing.briefing_text)
          ) : (
            <p className="text-sm text-blue-100 italic opacity-60">Good morning Monica. Use the sync button to prepare your daily strategy.</p>
          )}
        </div>

        <div className="grid grid-cols-3 gap-3">
          {[
            { label: 'Due Today', val: briefing?.stats?.due_followups ?? '...', icon: Clock, color: 'text-blue-400' },
            { label: 'Hot Expired', val: briefing?.stats?.hot_expired ?? '...', icon: Flame, color: 'text-red-400' },
            { label: 'Tasks', val: briefing?.stats?.tasks_due ?? '...', icon: CheckCircle, color: 'text-green-400' },
          ].map((s, i) => (
            <div key={i} className="bg-white/5 rounded-xl p-3 border border-white/5 text-center group hover:bg-white/10 transition-colors">
              <div className="flex items-center justify-center mb-1">
                <s.icon className={`h-3 w-3 opacity-60 mr-1.5 ${s.color}`} />
                <span className="text-[9px] font-black uppercase tracking-wider text-white/60">{s.label}</span>
              </div>
              <div className="text-xl font-black">{s.val}</div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  )
}
